name: Build, Push to GCR.
on:
  push:
    branches: 
    - staging
jobs:
  login-build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Log in to gcloud CLI
      run: gcloud auth configure-docker
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Write Dashboard Environment Variables
      run: |
        cat >./dashboard/.env <<EOL
        NODE_ENV=development
        API_SERVER=localhost:8080
        FULLSTORY_ORG_ID=${{secrets.FULLSTORY_ORG_ID}}
        DISCORD_KEY=${{secrets.DISCORD_KEY}}
        DISCORD_CID=${{secrets.DISCORD_CID}}
        FEEDBACK_ENDPOINT=${{secrets.FEEDBACK_ENDPOINT}}
        POSTHOG_API_KEY=${{secrets.POSTHOG_API_KEY}}
        POSTHOG_HOST=${{secrets.POSTHOG_HOST}}
        EOL
    - name: Build
      run: |
        DOCKER_BUILDKIT=1 docker build . -t gcr.io/porter-dev-273614/porter-prov:latest -f ./docker/Dockerfile
    - name: Push
      run: |
        docker push gcr.io/porter-dev-273614/porter-prov:latest
